name: user-service-ci

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/user-service
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 21 + Maven cache
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Run unit tests
        run: mvn -B test --no-transfer-progress

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push
        run: |
          mvn -B -pl web -am \
              -DskipTests \
              -Dspring-boot.build-image.publish=true \
              -Dspring-boot.build-image.imageName=${IMAGE_NAME}:${IMAGE_TAG} \
              spring-boot:build-image --no-transfer-progress

      - name: Notify k8s repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.K8S_REPO_TOKEN }}
          repository: LazarenkoDmytro/BlaBlaCark8s
          event-type: update-user-service
          client-payload: '{"tag":"${{ env.IMAGE_TAG }}"}'